# Generated by Django 3.1.4 on 2020-12-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_endpoint', '0002_auto_20201222_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='large',
            field=models.ImageField(blank=True, null=True, upload_to='static/large_avatars'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='small',
            field=models.ImageField(blank=True, null=True, upload_to='static/small_avatars'),
        ),
    ]
