# Generated by Django 3.1.4 on 2020-12-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_endpoint', '0003_auto_20201223_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='large',
            field=models.ImageField(blank=True, null=True, upload_to='large_avatars'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='small',
            field=models.ImageField(blank=True, null=True, upload_to='small_avatars'),
        ),
    ]
