# Generated by Django 3.1.4 on 2020-12-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_endpoint', '0004_auto_20201223_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uniqueUrlName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
